### ISSUE TITLE
Can't rename data npy files other than already given files

### ISSUE THREAD

**Issue by Purav-Zumkhawala** [khundman/telemanom#42]
Hi,

I can not name my data files any name other than already present channel names. Also, can you shed some light on how the npy file should be structured in case of uni-variate and multi-variate timeseries data showing a toy data like if we should include timestamps or just put the values one by one in different files as first dimension.

**Comment by khundman** [comment]
Please send the stack trace, I am unable to replicate any error with different channel names. Make sure you have properly setup `config.yaml` to train models for the new data otherwise it will look for existing models:

```yaml
# Runtime params
#===================================
train: True # train new or existing model for each channel
predict: True # generate new predicts or, if False, use predictions stored locally
use_id: ""
```

You would structure the numpy array the same way the experimental data is setup (for both univariate and multivariate). No timestamps are included, LSTMs are indifferent to the time between steps unless explicitly included as an input. More information on array shapes can be found here: https://github.com/khundman/telemanom#using-your-own-data
